// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate():Promise<main.Response>;

export function EscapeConver(arg1:string):Promise<main.Response>;

export function SelectFile():Promise<main.Response>;
