// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function EscapeConver(arg1) {
  return window['go']['main']['App']['EscapeConver'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
